{% set name = "evodag" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EvoDAG-{{ version }}.tar.gz
  sha256: 916adb91cf44b41bd42c6a556b960b7a53ef15325fb980c260224cf913235505

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - setuptools
    - sparsearray
    - pip
    - python
  run:
    - python
    - sparsearray

test:
  imports:
    - EvoDAG
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgraffg/EvoDAG
  summary: Evolving Directed Acyclic Graph (EvoDAG) is a steady-state Genetic Programming system with tournament selection
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
